### PR TITLE
Add a callback function for page naming

### PR DESCRIPTION
**Pull request by stezu**
This allows you to pass any number of things to use instead of a page
number. In my case I have a list of ~160 faculty that needs to be easy
to navigate. Numbering the pages doesn't make as much sense as splitting
it like so: A-C, C-F, G-H, etc. This function allows you to do more
complex changes like that, or even simpler ones like mapping language
translations.

### CODE REVIEW

**Comment by lekkerduidelijk** [comment]
@stezu Thanks for sharing, this looks like what I need. 
Do you have an implementation example to get it working with the A-C, C-F page labels?

**Comment by stezu** [comment]
```
var paginationOptions = {
    customValue: function (i, list) {
        var firstLetter = list.matchingItems[(i - 1) * list.page].values()['last'].charAt(0),
              lastLetter  = list.matchingItems[i * list.page - 1 < list.matchingItems.length ? i * list.page - 1 : list.matchingItems.length - 1].values()['last'].charAt(0);

        return firstLetter + ' - ' + lastLetter;
    },
};
```

This is the snippet of code I used. It finds the first and last item on the page and grabs the first character of the last name for those items.

**Comment by lekkerduidelijk** [comment]
Wow that was fast :smile:! Thanks a lot, I will try to implement this in my setup.

**Comment by stezu** [comment]
No problem, glad I could help.

**Pull request closed without merging**
